name: Simple Sanity Check

on:
  push:
    branches:
      - "main"
    paths:
      - '**/*.py'  # Run the job only when Python files change
      - 'Makefile'  # Run the job when Makefile changes
      - '.github/workflows/system-monitor.yml'  # Run the job when system-monitor.yml changes
  pull_request:
    branches:
      - "main"
    paths:
      - '**/*.py'  # Run the job only when Python files change
      - 'Makefile'  # Run the job when Makefile changes
      - '.github/workflows/system-monitor.yml'  # Run the job when system-monitor.yml changes

permissions:
  contents: read

jobs:
  build:
    name: Sanity Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Python 3.9, pipenv and Pipfile dependencies
        uses: palewire/install-python-pipenv-pipfile@v3
        with:
          python-version: "3.9.13"
      - name: Lint with Flake8
        run: pipenv run make lint
      - name: Test with Pytest
        run: pipenv run make test
